atlantico/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib.auth import views as auth_views
from moviesapp.api.viewsets import GenresViewSet, MoviesViewSet
from ratingsapp.api.viewsets import RatingsViewSet
from usersapp.api.viewsets import OccupationsViewSet, BasicUsersViewSet
from dashboard import urls as dashboard_urls

router = routers.DefaultRouter()
router.register(r'genres', GenresViewSet, base_name='Genre')
router.register(r'movies', MoviesViewSet, base_name='Movie')
router.register(r'occupations', OccupationsViewSet, base_name='Occupation')
router.register(r'users', BasicUsersViewSet, base_name='BasicUser')
router.register(r'ratings', RatingsViewSet, base_name='Rating')
router.register(r'recommendations', RatingsViewSet, base_name='Recommendation')


urlpatterns = [
    # Dashboard URLS
    path('', include(dashboard_urls, namespace='dashboard')),

    # ADMIN
    path('admin/', admin.site.urls),

    # API
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token),

    # Auth
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login'), name='logout'),
]

dashboard/urls.py
from django.urls import path
from dashboard import views as dashboard_views

app_name = "dashboard"

urlpatterns = [

    path('', dashboard_views.DashboardHome.as_view(), name='dashboard_home'),

    path('session_lost_check', dashboard_views.SessionLostCheck.as_view(), name='session_lost_check'),

    # BASIC USERS
    path('datatable/basic_users', dashboard_views.BasicUsersDatatable.as_view(), name='basic_users_dt'),
    path('basic_user/create', dashboard_views.BasicUserFormView.as_view(), name='basic_user_create'),

    # RATE MOVIES
    path('datatable/user/<pk>/ratings', dashboard_views.UserRatingsDatatable.as_view(), name='user_ratings_dt'),
    path('user/<pk>/ratings', dashboard_views.UserRatingsView.as_view(), name='user_ratings'),
    path('user/<pk>/top5', dashboard_views.UserTop5MoviesView.as_view(), name='user_top5'),


    path('datatable/movies', dashboard_views.MoviesDatatable.as_view(), name='movies_dt'),
    path('movies', dashboard_views.MoviesView.as_view(), name='movies'),
    path('movies/create', dashboard_views.MoviesFormView.as_view(), name='movie_create'),

]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms

from moviesapp.models import Movie
from ratingsapp.models import Rating
from usersapp.models import BasicUser


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ('user', 'movie', 'score')

class BasicUserForm(forms.ModelForm):
    class Meta:
        model = BasicUser
        fields = ('age', 'sex', 'occupation','zip_code')

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'release_date', 'video_release_date','imdb_url', 'genres')

dashboard/views.py
import time

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
import requests
from django.template.loader import render_to_string
from django.views import View
from django_datatables_view.base_datatable_view import BaseDatatableView
from rest_framework.authtoken.models import Token
from django.views.generic import TemplateView
from rest_framework.reverse import reverse

from core.models import Recommendation
from dashboard.forms import RatingForm, BasicUserForm, MovieForm
from dashboard.mixins import AjaxSaveAndResponseMixin
from moviesapp.models import Movie
from ratingsapp.models import Rating
from usersapp.models import BasicUser
from .tasks import similarity_ENGINE_JOB
from dashboard.helpers import DatatableTransformations as dt_helper


# Home Template View
class DashboardHome(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/home.html'

    def dispatch(self, request, *args, **kwargs):
        # If the user is authenticated add the token to the session
        if request.user.is_authenticated and 'api_token' not in request.session:
            token, _ = Token.objects.get_or_create(user=request.user)
            request.session['api_token'] = token.key
        return super().dispatch(request, *args, **kwargs)


# Basic Users Datatable
class BasicUsersDatatable(LoginRequiredMixin, BaseDatatableView):
    model = BasicUser
    columns = ['order',
               'sex',
               'age',
               'occupation',
               'zip_code',
               'created_at',
               'updated_at',
               'actions']

    max_display_length = 500

    def render_column(self, row, column):
        if column == 'order':
            return "USER_" + str(row.order)
        elif column == 'sex':
            if row.sex == 'M':
                return '<i class="fa fa-male"></i> MALE'
            elif row.sex == 'F':
                return '<i class="fa fa-female"></i> FEMALE'
        elif column == 'occupation':
            return dt_helper.highlightBlue(row.occupation.title.upper())
        elif column == 'created_at':
            return dt_helper.generateDateLabel(row.created_at)
        elif column == 'updated_at':
            return dt_helper.generateNaturalTime(row.updated_at, 'bg-red-flamingo bg-font-red-flamingo')
        elif column == 'actions':
            return render_to_string('basicusers/partial_users_dt.html', {"user": row, 'request': self.request})
        else:
            return super(BasicUsersDatatable, self).render_column(row, column)


# Basic if the user lost the session
class SessionLostCheck(View):

    def dispatch(self, request, *args, **kwargs):
        data = {
            'status': request.user.is_authenticated
        }
        return JsonResponse(data, status=200)


# Basic Users Form Creation
class BasicUserFormView(LoginRequiredMixin, AjaxSaveAndResponseMixin, View):
    template_name = 'basicusers/basic_users_form.html'
    modal_title = 'New Evaluator'
    model = BasicUser
    form_class = BasicUserForm
    form_fields = ['id', 'age', 'sex', 'zip_code']


class MoviesFormView(LoginRequiredMixin, AjaxSaveAndResponseMixin, View):
    template_name = 'movies/movie_form.html'
    modal_title = 'New Movie'
    model = Movie
    form_class = MovieForm
    form_fields = ['id', 'title', 'release_date', 'video_release_date', 'imdb_url']


# User Ratings Datatable
class UserRatingsDatatable(LoginRequiredMixin, BaseDatatableView):
    model = Movie
    columns = ['title',
               'release_date',
               'imdb_url',
               'genres',
               'rating'
               ]

    max_display_length = 500

    def dispatch(self, request, *args, **kwargs):
        self.basic_user = BasicUser.objects.get(id=kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def render_column(self, movie, column):

        if column == 'genres':
            html = ''
            for genre in movie.genres.all():
                html += '<span class="label label-default">' + genre.title + '</span>'
            return html
        elif column == 'release_date':
            if movie.release_date:
                return dt_helper.generateDateLabel(movie.release_date)
        elif column == 'rating':
            rating = Rating.objects.filter(movie=movie, user=self.basic_user)
            if rating.count():
                rating = rating.first()
            else:
                rating = None

            return render_to_string('ratings/partial_rating_stars.html', {"rating": rating,
                                                                          'movie': movie,
                                                                          'user': self.basic_user})
        elif column == 'imdb_url':
            return '<a target="_blank" href="' + movie.imdb_url + '"><button class="btn btn-primary btn-xs">IMDB URL <i class="fa fa-external-link-alt"></i></button></a>'
        else:
            return super(UserRatingsDatatable, self).render_column(movie, column)


# Movies Datatable
class MoviesDatatable(LoginRequiredMixin, BaseDatatableView):
    model = Movie
    columns = ['title',
               'release_date',
               'imdb_url',
               'genres',
               'ratings'
               ]

    max_display_length = 500

    def render_column(self, movie, column):

        if column == 'genres':
            html = ''
            for genre in movie.genres.all():
                html += '<span class="label label-default">' + genre.title + '</span>'
            return html
        elif column == 'release_date':
            if movie.release_date:
                return dt_helper.generateDateLabel(movie.release_date)
        elif column == 'ratings':
            return int(movie.ratings.count())
        elif column == 'imdb_url':
            return '<a target="_blank" href="' + movie.imdb_url + '"><button class="btn btn-primary btn-xs">IMDB URL <i class="fa fa-external-link-alt"></i></button></a>'
        else:
            return super(MoviesDatatable, self).render_column(movie, column)


# User Ratings Page
class UserRatingsView(LoginRequiredMixin, TemplateView):
    template_name = 'ratings/ratings.html'

    def dispatch(self, request, *args, **kwargs):
        self.basic_user = BasicUser.objects.get(id=kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['basic_user'] = self.basic_user
        return context


class UserTop5MoviesView(LoginRequiredMixin, TemplateView):
    template_name = 'basicusers/top5_movies.html'

    def dispatch(self, request, *args, **kwargs):
        self.basic_user = BasicUser.objects.get(id=kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['basic_user'] = self.basic_user
        context['top5'] = self.basic_user.recommendations.all().order_by('rank')
        return context


class MoviesView(LoginRequiredMixin, TemplateView):
    template_name = 'movies/movies.html'

dashboard/templates/ratings/partial_rating_stars.html
{% if rating is None %}
    <button class="btn btn-default btn-xs btn-block js-rate_movie"
            data-movie_id="{{ movie.id }}"
            data-user_id="{{ user.id }}"> Rate
    </button>
{% else %}
    <div class="stars">
        <select class="movie_rate" name="rating"
                autocomplete="off" data-movie_id="{{ movie.id }}"
                data-rating_id="{{ rating.id }}"
                data-user_id="{{ user.id }}">
            <option value="1" {% if rating.score == 1 %}selected{% endif %}>1</option>
            <option value="2" {% if rating.score == 2 %}selected{% endif %}>2</option>
            <option value="3" {% if rating.score == 3 %}selected{% endif %}>3</option>
            <option value="4" {% if rating.score == 4 %}selected{% endif %}>4</option>
            <option value="5" {% if rating.score == 5 %}selected{% endif %}>5</option>
        </select>
        <span class="stars_rate_value">{{ rating.score }}</span>
    </div>
{% endif %}

dashboard/templates/ratings/ratings.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    User Ratings | Dashboard
{% endblock %}

{% block content %}
    <!-- BEGIN PAGE HEADER-->

    <h1 class="page-title"><i class="fa fa-film"></i> Movies Recommedation System
        <small></small>
    </h1>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-users"></i>
                <a href="{% url 'dashboard:dashboard_home' %}">Evaluators</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <span><i class="fa fa-user"></i> USER_{{ basic_user.order }} Ratings</span>
            </li>

        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right">
                <button type="button" class="btn btn-fit-height blue dropdown-toggle" data-toggle="dropdown"
                        data-hover="dropdown" data-delay="1000" data-close-others="true"> Options
                    <i class="fa fa-angle-down"></i>
                </button>
                <ul class="dropdown-menu pull-right" role="menu">
                    <li>
                        <a id="add_new" href="/api/">
                            <i class="fa fa-database"></i> API
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- END PAGE HEADER-->

    <div class="row">
        <div class="col-md-8">
            <!-- BEGIN PORTLET-->
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-edit font-dark"></i>
                        <span class="caption-subject font-dark bold uppercase">USER_{{ basic_user.order }} Ratings List</span>
                    </div>
                    <div class="tools">
                        <a href="" class="collapse" data-original-title="" title=""> </a>
                        <a href="" class="remove" data-original-title="" title=""> </a>
                    </div>
                </div>
                <div class="portlet-body">
                    <section id="no-more-tables">
                        <table id="MainDatatable"
                               class="table table-striped table-bordered table-hover order-column dataTable no-footer">
                        </table>
                    </section>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="portlet box yellow-gold">
                <div class="portlet-title">
                    <div class="caption">
                        <b><i class="fa fa-film"></i> TOP 5 MOVIES </b>
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="fullscreen" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="remove" data-original-title="" title=""> </a>
                    </div>
                </div>
                <div class="portlet-body" style="">
                    <div id="top_5_user_panel"></div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block modals %}
    <!-- General Modal -->
    <div class="modal fade bs-modal-lg" id="general_modal" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
            </div>
        </div>
    </div>

{% endblock %}



<!-- CSS SCRIPTS -->
{% block CSS_PAGE_LEVEL_PLUGINS %}
    {% include 'plugins/simpledt_css_page_level_plugins.html' %}
{% endblock %}

{% block CSS_THEME_GLOBAL_STYLES %}
    {% include 'plugins/simpledt_css_theme_global_styles.html' %}
{% endblock %}

<!-- JS SCRIPTS -->
{% block JS_PAGE_LEVEL_PLUGINS %}
    {% include 'plugins/simpledt_js_page_level_plugins.html' %}
{% endblock %}



{% block JS_FINAL_SCRIPTS %}

    <script type="text/javascript">
        (function (window, $) {
            window.api_token = '{% if request.session.api_token %}{{ request.session.api_token }}{% endif %}';
            window.user_ratings_dt = "{% url 'dashboard:user_ratings_dt' basic_user.id %}";
            window.api_rating_url = "{{ request.scheme }}://{{ request.get_host }}{% url 'Rating-list' %}"
            window.user_top5_url = "{% url 'dashboard:user_top5' basic_user.id %}";

        })(window, jQuery);
    </script>
    <script src="{% static 'js/helper_components.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/common_dt.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/user_ratings_dt.js' %}" type="text/javascript"></script>

{% endblock %}