atlantico/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib.auth import views as auth_views
from moviesapp.api.viewsets import GenresViewSet, MoviesViewSet
from ratingsapp.api.viewsets import RatingsViewSet
from usersapp.api.viewsets import OccupationsViewSet, BasicUsersViewSet
from dashboard import urls as dashboard_urls

router = routers.DefaultRouter()
router.register(r'genres', GenresViewSet, base_name='Genre')
router.register(r'movies', MoviesViewSet, base_name='Movie')
router.register(r'occupations', OccupationsViewSet, base_name='Occupation')
router.register(r'users', BasicUsersViewSet, base_name='BasicUser')
router.register(r'ratings', RatingsViewSet, base_name='Rating')
router.register(r'recommendations', RatingsViewSet, base_name='Recommendation')


urlpatterns = [
    # Dashboard URLS
    path('', include(dashboard_urls, namespace='dashboard')),

    # ADMIN
    path('admin/', admin.site.urls),

    # API
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token),

    # Auth
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login'), name='logout'),
]

dashboard/urls.py
from django.urls import path
from dashboard import views as dashboard_views

app_name = "dashboard"

urlpatterns = [

    path('', dashboard_views.DashboardHome.as_view(), name='dashboard_home'),

    path('session_lost_check', dashboard_views.SessionLostCheck.as_view(), name='session_lost_check'),

    # BASIC USERS
    path('datatable/basic_users', dashboard_views.BasicUsersDatatable.as_view(), name='basic_users_dt'),
    path('basic_user/create', dashboard_views.BasicUserFormView.as_view(), name='basic_user_create'),

    # RATE MOVIES
    path('datatable/user/<pk>/ratings', dashboard_views.UserRatingsDatatable.as_view(), name='user_ratings_dt'),
    path('user/<pk>/ratings', dashboard_views.UserRatingsView.as_view(), name='user_ratings'),
    path('user/<pk>/top5', dashboard_views.UserTop5MoviesView.as_view(), name='user_top5'),


    path('datatable/movies', dashboard_views.MoviesDatatable.as_view(), name='movies_dt'),
    path('movies', dashboard_views.MoviesView.as_view(), name='movies'),
    path('movies/create', dashboard_views.MoviesFormView.as_view(), name='movie_create'),

]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms

from moviesapp.models import Movie
from ratingsapp.models import Rating
from usersapp.models import BasicUser


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ('user', 'movie', 'score')

class BasicUserForm(forms.ModelForm):
    class Meta:
        model = BasicUser
        fields = ('age', 'sex', 'occupation','zip_code')

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'release_date', 'video_release_date','imdb_url', 'genres')

dashboard/views.py
import time

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
import requests
from django.template.loader import render_to_string
from django.views import View
from django_datatables_view.base_datatable_view import BaseDatatableView
from rest_framework.authtoken.models import Token
from django.views.generic import TemplateView
from rest_framework.reverse import reverse

from core.models import Recommendation
from dashboard.forms import RatingForm, BasicUserForm, MovieForm
from dashboard.mixins import AjaxSaveAndResponseMixin
from moviesapp.models import Movie
from ratingsapp.models import Rating
from usersapp.models import BasicUser
from .tasks import similarity_ENGINE_JOB
from dashboard.helpers import DatatableTransformations as dt_helper


# Home Template View
class DashboardHome(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/home.html'

    def dispatch(self, request, *args, **kwargs):
        # If the user is authenticated add the token to the session
        if request.user.is_authenticated and 'api_token' not in request.session:
            token, _ = Token.objects.get_or_create(user=request.user)
            request.session['api_token'] = token.key
        return super().dispatch(request, *args, **kwargs)


# Basic Users Datatable
class BasicUsersDatatable(LoginRequiredMixin, BaseDatatableView):
    model = BasicUser
    columns = ['order',
               'sex',
               'age',
               'occupation',
               'zip_code',
               'created_at',
               'updated_at',
               'actions']

    max_display_length = 500

    def render_column(self, row, column):
        if column == 'order':
            return "USER_" + str(row.order)
        elif column == 'sex':
            if row.sex == 'M':
                return '<i class="fa fa-male"></i> MALE'
            elif row.sex == 'F':
                return '<i class="fa fa-female"></i> FEMALE'
        elif column == 'occupation':
            return dt_helper.highlightBlue(row.occupation.title.upper())
        elif column == 'created_at':
            return dt_helper.generateDateLabel(row.created_at)
        elif column == 'updated_at':
            return dt_helper.generateNaturalTime(row.updated_at, 'bg-red-flamingo bg-font-red-flamingo')
        elif column == 'actions':
            return render_to_string('basicusers/partial_users_dt.html', {"user": row, 'request': self.request})
        else:
            return super(BasicUsersDatatable, self).render_column(row, column)


# Basic if the user lost the session
class SessionLostCheck(View):

    def dispatch(self, request, *args, **kwargs):
        data = {
            'status': request.user.is_authenticated
        }
        return JsonResponse(data, status=200)


# Basic Users Form Creation
class BasicUserFormView(LoginRequiredMixin, AjaxSaveAndResponseMixin, View):
    template_name = 'basicusers/basic_users_form.html'
    modal_title = 'New Evaluator'
    model = BasicUser
    form_class = BasicUserForm
    form_fields = ['id', 'age', 'sex', 'zip_code']


class MoviesFormView(LoginRequiredMixin, AjaxSaveAndResponseMixin, View):
    template_name = 'movies/movie_form.html'
    modal_title = 'New Movie'
    model = Movie
    form_class = MovieForm
    form_fields = ['id', 'title', 'release_date', 'video_release_date', 'imdb_url']


# User Ratings Datatable
class UserRatingsDatatable(LoginRequiredMixin, BaseDatatableView):
    model = Movie
    columns = ['title',
               'release_date',
               'imdb_url',
               'genres',
               'rating'
               ]

    max_display_length = 500

    def dispatch(self, request, *args, **kwargs):
        self.basic_user = BasicUser.objects.get(id=kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def render_column(self, movie, column):

        if column == 'genres':
            html = ''
            for genre in movie.genres.all():
                html += '<span class="label label-default">' + genre.title + '</span>'
            return html
        elif column == 'release_date':
            if movie.release_date:
                return dt_helper.generateDateLabel(movie.release_date)
        elif column == 'rating':
            rating = Rating.objects.filter(movie=movie, user=self.basic_user)
            if rating.count():
                rating = rating.first()
            else:
                rating = None

            return render_to_string('ratings/partial_rating_stars.html', {"rating": rating,
                                                                          'movie': movie,
                                                                          'user': self.basic_user})
        elif column == 'imdb_url':
            return '<a target="_blank" href="' + movie.imdb_url + '"><button class="btn btn-primary btn-xs">IMDB URL <i class="fa fa-external-link-alt"></i></button></a>'
        else:
            return super(UserRatingsDatatable, self).render_column(movie, column)


# Movies Datatable
class MoviesDatatable(LoginRequiredMixin, BaseDatatableView):
    model = Movie
    columns = ['title',
               'release_date',
               'imdb_url',
               'genres',
               'ratings'
               ]

    max_display_length = 500

    def render_column(self, movie, column):

        if column == 'genres':
            html = ''
            for genre in movie.genres.all():
                html += '<span class="label label-default">' + genre.title + '</span>'
            return html
        elif column == 'release_date':
            if movie.release_date:
                return dt_helper.generateDateLabel(movie.release_date)
        elif column == 'ratings':
            return int(movie.ratings.count())
        elif column == 'imdb_url':
            return '<a target="_blank" href="' + movie.imdb_url + '"><button class="btn btn-primary btn-xs">IMDB URL <i class="fa fa-external-link-alt"></i></button></a>'
        else:
            return super(MoviesDatatable, self).render_column(movie, column)


# User Ratings Page
class UserRatingsView(LoginRequiredMixin, TemplateView):
    template_name = 'ratings/ratings.html'

    def dispatch(self, request, *args, **kwargs):
        self.basic_user = BasicUser.objects.get(id=kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['basic_user'] = self.basic_user
        return context


class UserTop5MoviesView(LoginRequiredMixin, TemplateView):
    template_name = 'basicusers/top5_movies.html'

    def dispatch(self, request, *args, **kwargs):
        self.basic_user = BasicUser.objects.get(id=kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['basic_user'] = self.basic_user
        context['top5'] = self.basic_user.recommendations.all().order_by('rank')
        return context


class MoviesView(LoginRequiredMixin, TemplateView):
    template_name = 'movies/movies.html'

dashboard/templates/basicusers/basic_users_form.html
{% load widget_tweaks %}

<form class="form form-horizontal" method="POST" action="{{ request_path }}" id="js-basic-user-form" novalidate>
    {% csrf_token %}

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title">{{ modal_title }}</h4>
    </div>
    <div class="modal-body">


        {% for field in form %}

            <div class="form-group{% if field.errors %} has-error{% endif %} {{ field|field_type }} {{ field|widget_type }} {{ field.html_name }}">

                <label class="col-md-3" for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="col-lg-9">
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>

        {% endfor %}


    </div>
    <div class="modal-footer">
        <button type="button" class="btn_cancel btn dark btn-outline" data-dismiss="modal">Close</button>
        <button type="submit" class="btn_confirm btn green">Save</button>
    </div>
</form>

dashboard/templates/basicusers/partial_users_dt.html
<a href="{% url 'dashboard:user_ratings' user.id %}"
   class="js-edit-group btn btn-primary btn-sm">
    <i class="fa fa-star"></i> Rate Movies
</a>

<a href="javascript:;"
   class="js-remove-item btn btn-primary btn-sm btn-danger"
   data-user_order="{{ user.order }}"
   data-url="{{ request.scheme }}://{{ request.get_host }}{% url 'BasicUser-list' %}{{ user.id }}"
   data-modal="#general_modal">
    <i class="fa fa-trash"></i>
</a>

dashboard/templates/basicusers/top5_movies.html
{% if top5 %}
    <div class="row">

        <div class="col-lg-12">
            <div class="table-scrollable">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th> Rank</th>
                        <th> Movie</th>
                        <th> Score</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for recommendation in top5 %}
                        <tr>
                            <td><b> {{ recommendation.rank }}</b></td>
                            <td> {{ recommendation.movie.title }}</td>
                            <td>
                                <span class="score_rating_top_5">{{ recommendation.score|stringformat:"0.2f" }}</span>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>

    </div>
{% else %}
    <div class="note note-info">
        <h4 class="block">Start Rating <i class="fa fa-star"></i></h4>
        <p> Seems like this user has no any recommendation yet. Please, start rating to see new recommendations
            here. </p>
    </div>
{% endif %}

    <div class="row">

        <div class="col-lg-12">
            <div class="form-group">
                <button class="btn yellow-gold uppercase  reload_top_5_btn"><i class="fa fa-refresh"></i>
                    RELOAD
                </button>
            </div>
        </div>
    </div>